name: 'terraform'

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

env:
  TERRAFORM_VERSION: '1.7.0'
  TFDOCS_VERSION: '0.20.0'

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  terraform_lint:
    uses: 'abcxyz/actions/.github/workflows/terraform-lint.yml@main' # ratchet:exclude
    with:
      directory: './modules'
      terraform_version: '1.7.0'

  terraform_docs:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11' # ratchet:actions/checkout@v4

      - name: 'Setup terraform-docs'
        uses: 'abcxyz/actions/.github/actions/setup-binary@main' # ratchet:exclude
        with:
          download_url: 'https://github.com/terraform-docs/terraform-docs/releases/download/v${{ env.TFDOCS_VERSION }}/terraform-docs-v${{ env.TFDOCS_VERSION }}-linux-amd64.tar.gz'
          checksum: '34ae01772412bb11474e6718ea62113e38ff5964ee570a98c69fafe3a6dff286'
          install_path: '${{ runner.temp }}/.terraform-docs'
          binary_subpath: 'terraform-docs'
          cache_key: '${{ runner.os }}_${{ runner.arch }}_terraform-docs_${{ env.TFDOCS_VERSION }}'
          add_to_path: true

      - name: 'Validate Docs'
        shell: 'bash'
        run: |-
          terraform-docs .

          DIFF=$(git status --porcelain)

          if [ -n "${DIFF}" ]; then
            echo "ERROR: The following files differ from the pull request:"
            echo ""
            echo "${DIFF}"
            echo ""
            echo "::error ::Diff found for configured Terraform modules"
            exit 1
          fi
